version: '3.9'
services:

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050



  app:
   build: .
   container_name: app
   image: go-chat:v1
   environment:
     POSTGRES_USERNAME: postgres
     POSTGRES_PASSWORD: pass
     POSTGRES_HOST: postgres
     REDIS_ADDRESS: redispkg:6379
     REDIS_PASSWORD: passwordRedis
     DISABLE_SWAGGER_HTTP_HANDLER: true
     GIN_MODE: release
     EDENAI_APIKEY: asdsda
     APP_VERSION: 1.0.0
     HTTP_PORT: 8080
     LOG_LEVEL: debug

   ports:
     - 8080:8080
   depends_on:
     - postgres


  redis:
    image: redis:7.0.1-alpine3.16
    container_name: redispkg
    hostname: redispkg
    restart: always
    ports:
      - 6378:6379
    command: >
      --requirepass passwordRedis


volumes:
  pg-data:
