app:
  name: 'go-chat-api'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-chat-api'

postgres:
  pool_max: 2
  username: postgres
  password: pass



redis:
  server_address: ':6379'
  host: chat-redispkg #gak guna
  address: 6379 #gak guna
  password: passwordRedis #gak guna
