app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2
  username: postgres
  password: pass



redis:
  server_address: ':6379'
  host: chat-redispkg
  address: 6379
  password: passwordRedis
